-- MySQL Script generated by MySQL Workbench
-- Sun Apr 19 13:05:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BolValdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BolValdb` ;

-- -----------------------------------------------------
-- Schema BolValdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BolValdb` DEFAULT CHARACTER SET utf8 ;
USE `BolValdb` ;

-- -----------------------------------------------------
-- Table `BolValdb`.`tb_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolValdb`.`tb_empresa` ;

CREATE TABLE IF NOT EXISTS `BolValdb`.`tb_empresa` (
  `num_cnpj` VARCHAR(14) NOT NULL,
  `nome_empresa` VARCHAR(60) NOT NULL,
  `setor_atuacao` VARCHAR(60) NULL,
  `valor_mercado` VARCHAR(45) NULL,
  PRIMARY KEY (`num_cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolValdb`.`tb_acao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolValdb`.`tb_acao` ;

CREATE TABLE IF NOT EXISTS `BolValdb`.`tb_acao` (
  `ticker` VARCHAR(10) NOT NULL,
  `tb_empresa_num_cnpj` VARCHAR(14) NOT NULL,
  `cotacao_atual` FLOAT NULL,
  PRIMARY KEY (`ticker`),
  INDEX `fk_tb_acao_tb_empresa_idx` (`tb_empresa_num_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_tb_acao_tb_empresa`
    FOREIGN KEY (`tb_empresa_num_cnpj`)
    REFERENCES `BolValdb`.`tb_empresa` (`num_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolValdb`.`tb_cotacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolValdb`.`tb_cotacao` ;

CREATE TABLE IF NOT EXISTS `BolValdb`.`tb_cotacao` (
  `id_cotacao` INT NOT NULL AUTO_INCREMENT,
  `tb_acao_ticker` VARCHAR(10) NOT NULL,
  `data_hora_cotacao` DATETIME NULL,
  `valor_cotacao` FLOAT NULL,
  INDEX `fk_tb_cotacao_tb_acao1_idx` (`tb_acao_ticker` ASC) VISIBLE,
  PRIMARY KEY (`id_cotacao`),
  CONSTRAINT `fk_tb_cotacao_tb_acao1`
    FOREIGN KEY (`tb_acao_ticker`)
    REFERENCES `BolValdb`.`tb_acao` (`ticker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolValdb`.`tb_investidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolValdb`.`tb_investidor` ;

CREATE TABLE IF NOT EXISTS `BolValdb`.`tb_investidor` (
  `cod_documento` VARCHAR(14) NOT NULL,
  `nome_completo` VARCHAR(60) NOT NULL,
  `tipo_investidor` ENUM('PF', 'PJ') NOT NULL,
  `numero_telefone` VARCHAR(15) NULL,
  `email` VARCHAR(20) NULL,
  `saldo_quantidade_acoes` INT NULL,
  PRIMARY KEY (`cod_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolValdb`.`tb_negocia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolValdb`.`tb_negocia` ;

CREATE TABLE IF NOT EXISTS `BolValdb`.`tb_negocia` (
  `id_negocia` INT NOT NULL AUTO_INCREMENT,
  `tb_investidor_cod_documento` VARCHAR(14) NOT NULL,
  `tb_acao_ticker` VARCHAR(10) NOT NULL,
  `tipo_operacao` ENUM('C', 'V') NOT NULL,
  `quantidade_acoes` INT NULL,
  `valor_unitario_acao` FLOAT NULL,
  `data_hora_transacao` DATETIME NULL,
  INDEX `fk_tb_negocia_tb_acao1_idx` (`tb_acao_ticker` ASC) VISIBLE,
  INDEX `fk_tb_negocia_tb_investidor1_idx` (`tb_investidor_cod_documento` ASC) VISIBLE,
  PRIMARY KEY (`id_negocia`),
  CONSTRAINT `fk_tb_investidor_has_tb_acao_tb_investidor1`
    FOREIGN KEY (`tb_investidor_cod_documento`)
    REFERENCES `BolValdb`.`tb_investidor` (`cod_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_investidor_has_tb_acao_tb_acao1`
    FOREIGN KEY (`tb_acao_ticker`)
    REFERENCES `BolValdb`.`tb_acao` (`ticker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
